# -*- coding: utf-8 -*-
"""LR_1_Task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hy3CXYRgE8KUMy20PJ1D2l31UcIRE5j9
"""

def and_func(x1, x2):
    return x1 and x2

def or_func(x1, x2):
    return x1 or x2

def xor(x1, x2):
    return int(or_func(x1, x2) and not and_func(x1, x2))

print(xor(0, 0)) #0
print(xor(0, 1)) #1
print(xor(1, 0)) #1
print(xor(1, 1)) #0